name: Run Tests

on:
  push:
    branches:
      - main  # or the branch you want to trigger the action
  pull_request:
    branches:
      - main  # or the branch you want to trigger the action

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies for Python projects

    - name: Run tests
      run: |
        pytest  # Replace with the command to run your tests