name: Check Hugging Face Space Update

on:
  push:
    branches:
      - main  # or the branch you want to trigger the action

jobs:
  check-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install requests  # Install requests library to interact with APIs

    - name: Check if Hugging Face Space was updated
      env:
        HF_SPACE_URL: ${{ secrets.HF_SPACE_URL }}
        HF_API_KEY: ${{ secrets.HF_TOKEN }}
      run: |
        python check_update.py